version: "3"

services:
  db:
    image: postgres:10
    environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
  web:
    build: .
    volumes:
      - .:/code
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - db